// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Debug provides a mock function with given fields: ctx, message, fields
func (_m *Logger) Debug(ctx context.Context, message string, fields ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, message)
	_ca = append(_ca, fields...)
	_m.Called(_ca...)
}

// Error provides a mock function with given fields: ctx, message, fields
func (_m *Logger) Error(ctx context.Context, message string, fields ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, message)
	_ca = append(_ca, fields...)
	_m.Called(_ca...)
}

// Fatal provides a mock function with given fields: ctx, message, fields
func (_m *Logger) Fatal(ctx context.Context, message string, fields ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, message)
	_ca = append(_ca, fields...)
	_m.Called(_ca...)
}

// Info provides a mock function with given fields: ctx, message, fields
func (_m *Logger) Info(ctx context.Context, message string, fields ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, message)
	_ca = append(_ca, fields...)
	_m.Called(_ca...)
}

// Panic provides a mock function with given fields: ctx, message, fields
func (_m *Logger) Panic(ctx context.Context, message string, fields ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, message)
	_ca = append(_ca, fields...)
	_m.Called(_ca...)
}

// Warn provides a mock function with given fields: ctx, message, fields
func (_m *Logger) Warn(ctx context.Context, message string, fields ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, message)
	_ca = append(_ca, fields...)
	_m.Called(_ca...)
}

type mockConstructorTestingTNewLogger interface {
	mock.TestingT
	Cleanup(func())
}

// NewLogger creates a new instance of Logger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLogger(t mockConstructorTestingTNewLogger) *Logger {
	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
